### ISSUE TITLE
Business Scenario

### ISSUE THREAD

**Issue by petruki** [douglas-softeng/mytable-app#1]
The following section must be produced:
[Business Scenario](https://github.com/douglas-softeng/mytable-app/wiki/Project-Proposal:-Business-Scenario)

**Comment by bajwap36** [comment]
> The following section must be produced:
> [Business Scenario](https://github.com/douglas-softeng/mytable-app/wiki/Project-Proposal:-Business-Scenario)

Business Scenario  

MyTable application is designed to improve the overall management of the restaurant as well as providing customers a greater sense of ease to access the booking services.
Keeping a manual track of the bookings is time consuming, unreliable and more prone to errors. Such unorganized data also makes it difficult for the management to make accurate business decisions in future. The purpose of MyTable application is to eradicate all above mentioned problems. MyTable allows the restaurant to keep track of current availability of tables, information about booked tables and contact information of customers.
In the customer view, making and managing bookings earlier without the app could only be performed by visiting in person or through phone calls at opening hours only. This method involves a lot of non transparency and is time consuming. Whereas, MyTable provides customers the comfort to check availability of tables, make new bookings, manage current bookings or cancellation, at any hour with ease. 
In addition, MyTable also keeps the history stored about all the bookings made along with customer data, to be used for analytics in future. The data is well-organized which makes the task of generating progress reports, discovering the shortcomings and management of staff & resources much more efficient. In a long run, this data provides a huge assistance in making important business decisions.
