### ISSUE TITLE
Identify potential stakeholders

### ISSUE THREAD

**Issue by petruki** [douglas-softeng/mytable-app#2]
The following section must be produced:
[Identifying potential stakeholders](https://github.com/douglas-softeng/mytable-app/wiki/Project-Proposal:-Identifying-potential-stakeholders)

**Comment by rohansingla1994** [comment]
Potential Stakeholders for this Application are as follows 
1) Restaurant Manager - Interest of the restaurant manager is to manage the MyTable App. 
2) Executive - Interest of the Executive is they should be kept informed with business decisions.
3) Crew members - Interest of the crew members is they should be monitored.
4) Programmers - Interest of the Programmers is they should be managed closely.
5) End Users - Power of the Programmers is they should be kept satisfied with the food and waiting time.
6) Business investors - Power of the Programmers is they should be kept satisfied with profits.
7) Suppliers - Interest of the suppliers is they should be monitored with the quality ingredients.
8) Business Partners - Interest of the crew members is they should be informed and kept satisfied.
