### ISSUE TITLE
Development of Use Case

### ISSUE THREAD

**Issue by petruki** [douglas-softeng/mytable-app#5]
Produce content at:
https://github.com/douglas-softeng/mytable-app/wiki/System-Analysis:-Development-of-Use-Case

**Comment by rohansingla1994** [comment]
[Use case diagram my table.pdf](https://github.com/douglas-softeng/mytable-app/files/6133712/Use.case.diagram.my.table.pdf)

**Comment by rohansingla1994** [comment]
Please verify the use case Diagram
