### ISSUE TITLE
Defining DB Schema

### ISSUE THREAD

**Issue by petruki** [douglas-softeng/mytable-app#7]
Produce content at:
https://github.com/douglas-softeng/mytable-app/wiki/System-Analysis:-Defining-DB-schema

**Comment by rohansingla1994** [comment]
1) Customer   ID | Name | Password | Email

2) Resturantid | Restname | Total Tables available in resturant | Available Tables

3) Booking id | Custid | Restid | No of tables booked

**Comment by rohansingla1994** [comment]
Kindly Give remarks

**Comment by petruki** [comment]
Could please move the content to the Wiki page. The link is on the issue's body for reference.

**Comment by rohansingla1994** [comment]
done
